language: node_js
node_js:
  - '0.12'
  - 'stable'
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - 'npm upgrade -g npm'
script:
  - 'npm run travis'
after_script:
  - 'cat ./coverage/lcov.info | coveralls'
