var test = require('tape')
var check = require('../../lib/quiz/check-answer.js')

test('check-answer', function (t) {
  t.ok(check('salmonella', 'salmonella'), 'exact things match')
  t.ok(check('salmonella', 'salmonell'), 'forgetting the last character is ok')
  t.not(check('salmonell', 'salmonella'), 'adding a character is not ok')

  t.ok(check('a check', 'check'), 'ignores "a" in the beginning of answer')
  t.not(check('check a', 'check'), 'doesn\'t ignore an "a" that isn\'t in the beginning of the answer')
  t.ok(check('A check', 'check'), 'ignores "A" in the beginning of answer')
  t.not(check('check A', 'check'), 'doesn\'t ignore an "A" that isn\'t in the beginning of the answer')
  t.ok(check('check', 'a check'), 'ignores "a" in the beginning of response')
  t.not(check('check', 'check a'), 'doesn\'t ignore an "a" that isn\'t in the beginning of the response')
  t.ok(check('check', 'A check'), 'ignores "A" in the beginning of response')
  t.not(check('check', 'check A'), 'doesn\'t ignore an "A" that isn\'t in the beginning of the response')
  t.ok(check('an check', 'check'), 'ignores "an" in the beginning of answer')
  t.not(check('check an', 'check'), 'doesn\'t ignore an "an" that isn\'t in the beginning of the answer')
  t.ok(check('An check', 'check'), 'ignores "An" in the beginning of answer')
  t.not(check('check An', 'check'), 'doesn\'t ignore an "An" that isn\'t in the beginning of the answer')
  t.ok(check('check', 'an check'), 'ignores "an" in the beginning of response')
  t.not(check('check', 'check an'), 'doesn\'t ignore an "an" that isn\'t in the beginning of the response')
  t.ok(check('check', 'An check'), 'ignores "An" in the beginning of response')
  t.not(check('check', 'check An'), 'doesn\'t ignore an "An" that isn\'t in the beginning of the response')
  t.ok(check('the check', 'check'), 'ignores "the" in the beginning of answer')
  t.not(check('check the', 'check'), 'doesn\'t ignore a "the" that isn\'t in the beginning of the answer')
  t.ok(check('The check', 'check'), 'ignores "The" in the beginning of answer')
  t.not(check('check The', 'check'), 'doesn\'t ignore a "The" that isn\'t in the beginning of the answer')
  t.ok(check('check', 'the check'), 'ignores "the" in the beginning of response')
  t.not(check('check', 'check the'), 'doesn\'t ignore a "the" that isn\'t in the beginning of the response')
  t.ok(check('check', 'The check'), 'ignores "The" in the beginning of response')
  t.not(check('check', 'Theck the'), 'doesn\'t ignore a "The" that isn\'t in the beginning of the response')

  t.ok(check('chEqUe', 'CHeQuE'), 'case-insensitive')
  t.ok(check('chEqU e', 'CHe QuE'), 'space-insensitive')
  t.end()
})
